//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Rumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copa
    {
        public int IdCopa { get; set; }
        public string BebidaEscolhida { get; set; }
        public int Idpedido { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
